jobs:
  QuickChick:
    runs-on: ubuntu-latest
    steps:
    - name: Determine which commit to test
      run: "echo \"github evant_name = ${{ github.event_name }}\""
name: Nix CI for bundle coq-8.16
'on':
  pull_request:
    paths:
    - .github/workflows/**
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
  push:
    branches:
    - master
