jobs:
  QuickChick:
    runs-on: ubuntu-latest
    steps:
    - name: Determine which commit to test
      run: "if [ ${{ github.event_name }} = \"push\" ]; then\n  echo \"tested_commit=${{\
        \ github.sha }}\" >> $GITHUB_ENV\n  echo \"push\"\nelse\n  mergeable=$(git merge --no-commit --no-ff ${{ github.event.pull_request.head.sha }} > /dev/null; echo $?; git merge --abort > /dev/null)\n  echo \"mergeable = $mergeable\"\n  merge_commit=$(git ls-remote ${{\
        \ github.event.repository.html_url }} refs/pull/${{ github.event.number }}/merge\
        \ | cut -f1)\n  if [ -z \"$merge_commit\" -o \"x$mergeable\" != \"x0\" ]; then\n    echo \"tested_commit=${{\
        \ github.event.pull_request.head.sha }}\" >> $GITHUB_ENV\n    echo \"mergeable\"\n  else\n    echo\
        \ \"tested_commit=$merge_commit\" >> $GITHUB_ENV\n    echo \"not mergeable\"\n  fi\nfi\n"
name: Nix CI for bundle coq-8.16
'on':
  pull_request:
    paths:
    - .github/workflows/**
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
  push:
    branches:
    - master
